### ISSUE TITLE
VS Code install instructions or binary?

### ISSUE THREAD

**Issue by terriblefire** [BartmanAbyss/vscode-amiga-debug#1]
Fantastic project. I love the one stop shop idea. 

I'm a big VSCode user. However I cannot get the extension install. I dont even know where to start. 

What deps and steps are needed to get the vscode extension module built. Could we get a binary install package or even better integrate into the marget place?

**Comment by BartmanAbyss** [comment]
Just follow the instructions on the [release page](https://github.com/BartmanAbyss/vscode-amiga-debug/releases). No need to build it yourself ;)

**Comment by terriblefire** [comment]
Ah cool. Could you add that to the README.md

**Comment by BartmanAbyss** [comment]
Done.
