### ISSUE TITLE
Profiler frame progress isn't animated when capturing multiple frames.

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#101]
When capturing and profiling a single frame you can see all changes to any of the exposed resources. For example you can watch the blitter drawing lines cycle by cycle.

Is it possible for this to work when capturing multiple frames?

Maybe it would take up a lot of space and time? I'd still like it as an option if possible.

**Comment by BartmanAbyss** [comment]
Hmm.. should work for any frame in the multi-frame capture.. Probably broke something...

**Comment by rjobling** [comment]
Seems to work in the newest version.
