### ISSUE TITLE
Can default compiler path not be changed by the extension every now and then?

### ISSUE THREAD

**Issue by tehKaiN** [BartmanAbyss/vscode-amiga-debug#12]
The following lines gets added to .vscode/settings.json:

```json
	"C_Cpp.default.compilerPath": "path\\to\\m68k-amiga-elf-gcc.exe",
```

Which is not fine because it's also appended in non-amiga projects, including my work projects. I know I can disable extension for given workspace, but i don't need this line 95% of the time and I have 100+ projects on my disk. I keep removing it from non-amiga projects but that line comes back.

Perhaps this line could be added once when project gets created from template?

**Comment by BartmanAbyss** [comment]
yeah, that should only happen for amiga projects.
