### ISSUE TITLE
Can't use the image converter link

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#128]
The link opens the webpage in VSCode but then you can't save anything out of it I assume because the VSCode browser doesn't allow downloads.

**Comment by rjobling** [comment]
Same is probably true for other linked webpage tools.

**Comment by BartmanAbyss** [comment]
pinging @davidcanadas

**Comment by davidcanadas** [comment]
Don't know how to assign the issue to me. I'll take a look. If I can't find a proper solution, I'll provide a way to open tools needing uploads in external browsers.

**Comment by BartmanAbyss** [comment]
yeah, maybe just opening the link in a browser is enough?

**Comment by davidcanadas** [comment]
PRed.

**Comment by BartmanAbyss** [comment]
will be included in the upcoming 1.5.6 release
