### ISSUE TITLE
Non-Windows binaries not executable in published extension

### ISSUE THREAD

**Issue by grahambates** [BartmanAbyss/vscode-amiga-debug#138]
When installing the extension from VS Code Marketplace none of the binaries have executable permission set. I'm guessing this is because the published package was built on Windows and the POSIX permissions were lost.

Options I can think of:
- A: Publish from your Linux box. I'm guessing this is a major inconvenience in the long run. Might be a quick fix for now though.
- B: Automate publishing from CI. This would be nice but probably a bit of effort to set up.
- C: Have the extension chmod the files to ensure they're executable on init. I'm happy to implement this if you want to go this route.

**Comment by BartmanAbyss** [comment]
Yeah, I was wondering about that, given that .vsix files are just renamed .zip files.
I guess 'C' would be the easiest..
