### ISSUE TITLE
Example: main.c and support/gcc8_c_support.c cannot be found

### ISSUE THREAD

**Issue by sebastianbergmann** [BartmanAbyss/vscode-amiga-debug#139]
I followed the [quick start](https://github.com/BartmanAbyss/vscode-amiga-debug#quick-start) instructions. When I hit `F5` then I get the output shown below:

```
 *  Task wird ausgeführt: c:\Users\sb\.vscode\extensions\bartmanabyss.amiga-debug-1.6.2\bin\win32\gnumake.exe -j4 program=out/a 

Compiling main.c
Compiling support/gcc8_c_support.c
Assembling support/gcc8_a_support.s
cc1.exe: fatal error: Example/main.c: No such file or directory
compilation terminated.
cc1.exe: fatal error: Example/support/gcc8_c_support.c: No such file or directory
compilation terminated.
gnumake: *** [Makefile:69: obj/main.o] Error 1
gnumake: *** Waiting for unfinished jobs....
gnumake: *** [Makefile:69: obj/gcc8_c_support.o] Error 1

 *  Der Terminalprozess "C:\Users\sb\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe -Command c:\Users\sb\.vscode\extensions\bartmanabyss.amiga-debug-1.6.2\bin\win32\gnumake.exe -j4 program=out/a" wurde mit folgendem Exitcode beendet: 1. 
```

#### Environment
* Windows 11 Pro 22H2
* Fresh installation of Visual Studio Code 1.72.2
* Fresh installation of version 1.6.2 of this extension

**Comment by BartmanAbyss** [comment]
oops. there seems to be some files there that shouldn't be... from VSCode open the "obj" folder and delete all files, then it should work. Will fix that in the next version.

**Comment by sebastianbergmann** [comment]
> from VSCode open the "obj" folder and delete all files, then do the same with the "out" folder. then it should work.

This unfortunately does not solve the issue for me.

**Comment by BartmanAbyss** [comment]
hmm.. It worked here. Any more info?

**Comment by sebastianbergmann** [comment]
Glad to provide more info, but don't know what you're looking for.

I deleted everything in `obj` and `out` and hit `F5`: same result.

I deleted everything, initialized a new Amiga project, deleted everything in `obj` and `out` and hit `F5`: same result.

**Comment by BartmanAbyss** [comment]
Hmm.. not sure. try to update to the latest 1.6.3? works fine here: https://we.tl/t-xUb3GwLC87

**Comment by sebastianbergmann** [comment]
Unfortunately same result with 1.6.3. Happy to hop on a video call with screenshare to figure this out collectively if that helps.

**Comment by BartmanAbyss** [comment]
sure. tonight around 20:00-ish?

**Comment by sebastianbergmann** [comment]
Works for me. How can I send you the URL for the video call?

**Comment by BartmanAbyss** [comment]
bartman (at) abyss-online (dot) de

**Comment by sebastianbergmann** [comment]
> bartman (at) abyss-online (dot) de

YSHM :)

**Comment by BartmanAbyss** [comment]
So for someone facing the same problem: don't have spaces in your directory names. gnumake can't handle it ;)

**Comment by sebastianbergmann** [comment]
Thank you so much!
