### ISSUE TITLE
Assembler debugging

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#14]
First of all thank you! This is incredible and has really given me the easy path I needed to revisit the Amiga.

I'm not sure if this is the appropriate place to ask questions but here goes.

When debugging C I'm sometimes able to single step through the assembly code, not sure if it works %100 but it certain is possible.

However if I write some inline asm code then I'm unable to single step through that code, it'll keep bouncing back to the C source.

Is this something would I can fix? Or is there something in the setup that would need to be improved?

**Comment by BartmanAbyss** [comment]
I think that's an inherent limitation of inline assembly. Maybe it works better if you put your assembly code into a separate .s file? We haven't used much assembly here, so I can't really comment on that issue. All the single-stepping etc. is handled by GDB.

**Comment by rjobling** [comment]
I don't know anything about how GDB works other than that it's a whole lot nicer than nothing! Seems like it would be hard to get it stepping through the inline code but maybe there's some way to have it step through the a.mingw.s code?

**Comment by BartmanAbyss** [comment]
It seems GDB can single step assembly instructions. See here: https://forum.qt.io/topic/35652/debugging-inline-assembly
I‘ll see if I can implement something like this.

**Comment by rjobling** [comment]
That would be wonderful! Thank you.

**Comment by BartmanAbyss** [comment]
Hey, I just checked that. If you select `Amiga: Set Force Disassembly` in the command-palette to `Forced`, the extension always shows assembly and you can now use the debugger's step function to step single instructions.

**Comment by rjobling** [comment]
That sounds good but I don't think I can use that with the 1.0 release I have. I'm not sure how to install the latest if I just pull the master zip from github here?

**Comment by BartmanAbyss** [comment]
That‘s already in 1.0

**Comment by BartmanAbyss** [comment]
You may want to have a look at the latest preview build.

**Comment by rjobling** [comment]
I didn't realize I needed to run the debugger first to get that command to show in the palette. But yes, it's there in 1.0. Will check out the preview. Seems like lots of good progress!

**Comment by BartmanAbyss** [comment]
Yeah, that's a setting that only affects the current debug session.

**Comment by rjobling** [comment]
I've been using this for debugging with 1.1.0 and wanted to share that it has been working really well! Thank you.

Doing a reasonable amount of assembler debugging makes me wish there were more ways to view registers. Would it be possible to expand the register view so it'll show the decimal values alongside the hex. And could it also show the values for upper/lower words or all four bytes? Would be very helpful if that isn't too difficult to add.
