### ISSUE TITLE
How do I add lz4_fastest.asm to sample project

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#144]
I'd like to test using Leonard's LZ4 depack code.

I thought with the new vasm support it'd be easy enough but I've run into a problem I don't understand.

Firstly in order to link I needed to change the main label so it has a double colon "lz4_depack::" that exposes the symbol.

But now I have an elf2hunk error:

Compiling main.c
Linking out/a.elf
Elf2Hunk out/a.exe
[ELF2HUNK] Unrecognized relocation type 187 2,
[ELF2HUNK]    for symbol ''
out/a.elf: Invalid argument
gnumake: *** [Makefile:46: out/a.exe] Error 1

Any ideas?

Leonard's code is here: https://github.com/arnaud-carre/lz4-68k

**Comment by rjobling** [comment]
I gave up on trying to compile this as a .asm file and just converted the lib to a .s file and that worked for me.

I suspect that the vasm support doesn't play nice with cpp files and therefore c++?

**Comment by BartmanAbyss** [comment]
I don't know. I can't think of a simple reason. But I haven't used vasm, https://github.com/davidcanadas implemented the support for it.

**Comment by rjobling** [comment]
.s version is fine for my purposes
