### ISSUE TITLE
No optimisation since 1.6.3

### ISSUE THREAD

**Issue by rveilleux** [BartmanAbyss/vscode-amiga-debug#146]
Hi Bartman,

I noticed that since the update to 1.6.3 that happened yesterday, my builds are no longer optimized. It looks like it is always compiling in debug mode, whatever cmake build variant I select. (Note: it might be an issue on my side, I'm just mentioning here as a 'heads-up' in case someone else also reports a similar situation).

My workaround was to reinstall 1.6.1, since the 1.6.2 and 1.6.3 are only adding linux/mac support.
I'm sorry that I didn't investigate fully to provide more help.

**Comment by BartmanAbyss** [comment]
I think I'm missing some information here. 'cmake build variant'? don't know what's that. windows binaries of gcc haven't changed. Am thankful for any further informations.

**Comment by rveilleux** [comment]
Of course, sorry: I am using the ACE game engine https://github.com/AmigaPorts/ACE which includes instructions to use your bartman extension. 
The cmake variant are debug/release/etc.

Since version 1.6.2/1.6.3 changed some of the paths moving them under "win32", perhaps I missed something when I tried. I'll give it another try later and hopefully give you more information.

Rem.

**Comment by grahambates** [comment]
Just looking at the ACE instructions for CMake. There are a few places where you'll need to add the platform prefix:

```json5
    {
      // ...
      "compilers": {
        "C": "C:\\Users\\YOUR_USER_NAME\\.vscode\\extensions\\bartmanabyss.amiga-debug-1.6.3\\bin\\win32\\opt\\bin\\m68k-amiga-elf-gcc.exe",
        "CXX": "C:\\Users\\YOUR_USER_NAME\\.vscode\\extensions\\bartmanabyss.amiga-debug-1.6.3\\bin\\win32\\opt\\bin\\m68k-amiga-elf-gcc.exe"
      },
      "environmentVariables": {
        "PATH": "C:/Users/YOUR_USER_NAME/.vscode/extensions/bartmanabyss.amiga-debug-1.6.3/bin/win32/opt/bin;C:/Users/YOUR_USER_NAME/.vscode/extensions/bartmanabyss.amiga-debug-1.6.3/bin/win32;${env:PATH}"
      },
      "cmakeSettings": {
        // ...
        "TOOLCHAIN_PATH": "C:/Users/YOUR_USER_NAME/.vscode/extensions/bartmanabyss.amiga-debug-1.6.3/bin/win32/opt"
      },
    }
```

The directory structure should be the only thing that's changed on Windows though. It should be the same executables so it's a bit of a mystery to me why it would compile but be missing options. Maybe it's using another version of GCC / binutils on your path.

**Comment by rveilleux** [comment]
Quickly checking tonight, I got the 1.6.4 update, and it appears to lack several EXE files, for example:
m68k-amiga-elf-g++.exe is missing.
Comparing those two folders:
C:\Users\_YOUR_NAME_\.vscode\extensions\bartmanabyss.amiga-debug-1.6.3\bin\win32\opt\bin: 27 items
C:\Users\_YOUR_NAME_\.vscode\extensions\bartmanabyss.amiga-debug-1.6.4\bin\win32\opt\bin: 7 items.

I'll revert back to 1.6.3 regarding my original post.

**Comment by rveilleux** [comment]
> The directory structure should be the only thing that's changed on Windows though. It should be the same executables so it's a bit of a mystery to me why it would compile but be missing options. Maybe it's using another version of GCC / binutils on your path.

Thank you @grahambates, I think you were correct, I must have missed updating a line in that file: seems to be working perfectly fine now (on 1.6.3). I'll close this Comment and open a new one.
