### ISSUE TITLE
Initial project is missing player code when using Marketplace install

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#15]
I had been wondering how I was going to integrate a mod player, but it turns out your sample does this. However the samples generated from the Marketplace install don't include the mod player. Not sure why that is but it seemed worth mentioning.

**Comment by BartmanAbyss** [comment]
Thanks for the comment.
The next version isn't completed, so I haven't uploaded it to the marketplace. However, you can just get the contents of the 'template' folder from GitHub and use that with the marketplace version.

**Comment by BartmanAbyss** [comment]
You can have a look at the latest preview release
