### ISSUE TITLE
Profile File Size - no longer working

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#150]
Wasn't working for my project so I tried it using the sample and I get this error.

![image](https://user-images.githubusercontent.com/5326134/198861317-4e9b529f-5682-44e2-ab70-067f55f97e76.png)

**Comment by BartmanAbyss** [comment]
yep, that got broken in the last release. thanks for reporting. will be fixed in the next release.

**Comment by BartmanAbyss** [comment]
fixed in https://github.com/BartmanAbyss/vscode-amiga-debug/releases/tag/1.6.4
