### ISSUE TITLE
Sample includes two copies of doynax but does not use either?

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#151]
The sample includes duplicate .s and a .asm versions of the doynax code.

Only the .s code is hooked up with some inline code. But then that function is never called.

Would be nice to have a working example of using .asm files and using something like doynax.

The makefile is also hardcoded to only two specific .s files and it would be nice if it were more generic.

Not urgent but thought maybe you might like the feedback.

**Comment by BartmanAbyss** [comment]
Yeah, just an example on how to use assembly code. You're right, could do wildcards for .s files, but apparently nobody likes gas .s files, so the wildcard is just hooked up for vasm .asm files...

**Comment by BartmanAbyss** [comment]
I have wired up the VASM doynax code. Have a look here:
https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/template/main.c#L177
https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/template/support/depacker_doynax_vasm.asm
The makefile already supports building all `.asm` files (VASM), so probably it's a better idea to use `.asm` (VASM) than `.s` (GAS)
