### ISSUE TITLE
1.6.4 update missing some files?

### ISSUE THREAD

**Issue by rveilleux** [BartmanAbyss/vscode-amiga-debug#153]
Quickly checking tonight, I got the 1.6.4 update, and it appears to lack several EXE files, for example:
m68k-amiga-elf-g++.exe is missing.
Comparing those two folders:
`C:\Users\YOUR_NAME\.vscode\extensions\bartmanabyss.amiga-debug-1.6.3\bin\win32\opt\bin: 27 items
C:\Users\YOUR_NAME\.vscode\extensions\bartmanabyss.amiga-debug-1.6.4\bin\win32\opt\bin: 7 items.`

**Comment by BartmanAbyss** [comment]
Yeah, we cleaned up some unnecessary files. Do you really need *-g++? Why not just use *-gcc?

**Comment by rveilleux** [comment]
Indeed, that could work; however, g++ has implicit options for compiling c++ (versus gcc which targets C file, even if it can handle .CPP files too).
I'll close this issue anyway with your suggestion (and since I'll only C in my game)

**Comment by BartmanAbyss** [comment]
'gcc' detects C or C++ based on the file extension, that should be fine 99% of the time, for all other cases, you can override the language standard with `-std=...` see https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html
