### ISSUE TITLE
Incompatible version libSDL2-2.0.0.dylib (Mac / fs-uae)

### ISSUE THREAD

**Issue by BangKarlsen** [BartmanAbyss/vscode-amiga-debug#157]
Hi, 
First of all thanks for the impressive work you're putting in this! I've been watching your progress on getting this to run on non-Windows from the side and it is awesome, and so close to working for me :) 

But. When I try to launch debug in VS Code I get an error "Emulator exited with code/signal SIGABRT before debugger could connect".

When I run fs-uae from command-line with`DYLD_FALLBACK_LIBRARY_PATH` set I get this error:

```
 ~/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5> DYLD_FALLBACK_LIBRARY_PATH=bin/darwin/fs-uae bin/darwin/fs-uae/fs-uae
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/hulkhojgaard/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5/bin/darwin/fs-uae/fs-uae
  Reason: Incompatible library version: fs-uae requires version 2401.0.0 or later, but libSDL2-2.0.0.dylib provides version 23.0.0
[1]    26230 abort      DYLD_FALLBACK_LIBRARY_PATH=bin/darwin/fs-uae bin/darwin/fs-uae/fs-uae
 ```
Is there a newer version of `libSDL2-2.0.0.dylib` that could be provided somehow?

I'm on OS X 10.14.6 if that's relevant.

Thank you.

**Comment by grahambates** [comment]
Thanks for reporting. I'll have a look at this.

**Comment by BangKarlsen** [comment]
Thank you for fixing it! Looking forward to try it out :)

**Comment by BangKarlsen** [comment]
Not sure if I should open a new issue or continue here, but writing here since the fix has not been released yet..

I did a test by downloading the new binary ([from here](https://github.com/BartmanAbyss/vscode-amiga-debug/blob/9bc064572c170ed87c57f25428ffe86279988428/bin/darwin/fs-uae/libSDL2-2.0.0.dylib)) but now I get the following error:
```sh
~/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5> DYLD_FALLBACK_LIBRARY_PATH=bin/darwin/fs-uae bin/darwin/fs-uae/fs-uae
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/hulkhojgaard/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5/bin/darwin/fs-uae/fs-uae
  Reason: no suitable image found.  Did find:
	bin/darwin/fs-uae/libSDL2-2.0.0.dylib: cannot load 'libSDL2-2.0.0.dylib' (load command 0x80000034 is unknown)
	/Users/hulkhojgaard/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5/bin/darwin/fs-uae/libSDL2-2.0.0.dylib: cannot load 'libSDL2-2.0.0.dylib' (load command 0x80000034 is unknown)
[1]    27622 abort      DYLD_FALLBACK_LIBRARY_PATH=bin/darwin/fs-uae bin/darwin/fs-uae/fs-uae
```
Googling it did not suggest how to fix it sadly.

**Comment by BangKarlsen** [comment]
I will upgrade my machine to newer version of OS X and see if that does anything.
