### ISSUE TITLE
Incompatible version `libSDL2_ttf-2.0.0.dylib` (Mac / fs-uae) 

### ISSUE THREAD

**Issue by BangKarlsen** [BartmanAbyss/vscode-amiga-debug#163]
Using v1.6.5 with newer version of `libSDL2-2.0.0.dylib` [(found here)](https://github.com/BartmanAbyss/vscode-amiga-debug/blob/9bc064572c170ed87c57f25428ffe86279988428/bin/darwin/fs-uae/libSDL2-2.0.0.dylib), which fixed the version issue in #157.

I now get the following error when manually running fs-uae:

```sh
 ~/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5: DYLD_FALLBACK_LIBRARY_PATH=bin/darwin/fs-uae bin/darwin/fs-uae/fs-uae
dyld: Library not loaded: /usr/local/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib
  Referenced from: /Users/hulkhojgaard/.vscode/extensions/bartmanabyss.amiga-debug-1.6.5/bin/darwin/fs-uae/fs-uae
  Reason: Incompatible library version: fs-uae requires version 2001.0.0 or later, but libSDL2_ttf-2.0.0.dylib provides version 15.0.0
```
Do you have a later version of `libSDL2_ttf-2.0.0.dylib` too?

Once again, thanks for working on this! 🙏

**Comment by grahambates** [comment]
Can you try [this version](https://github.com/grahambates/vscode-amiga-debug/raw/2dbc9b77a8ff36287f4a15a797ab11bf01cc995a/bin/darwin/fs-uae/libSDL2_ttf-2.0.0.dylib) to see if it fixes the problem and check whether there are any other libs that need upgrading?

**Comment by BangKarlsen** [comment]
Sure. Using that version did the trick:
<img width="1679" alt="Screenshot 2022-11-03 at 10 26 47" src="https://user-images.githubusercontent.com/1835444/199687281-d723f6ad-927d-47c7-bc44-0f455e9e0189.png">

Thanks for your quick response!
