### ISSUE TITLE
Option for not regeneration default.uae on launch

### ISSUE THREAD

**Issue by rveilleux** [BartmanAbyss/vscode-amiga-debug#165]
Hello Bartman,

When launching (thru F5) from VS Code to launch the debugger, the Bartman extension writes to **default.uae** in order to insert some values, like for example:
filesystem=rw,dh0:c:\Users\...
filesystem2=rw,dh1:dh1:C:\Users\...
kickstart_rom_file=...
debugging_features=gdbserver
debugging_trigger=:germz.exe

However, when trying to debug with other requirements, like for example loading from a floppy (floppy0=C:\Users\...) or specific CDTV and CD 32 extended rom and cd0image, this automatic overwrite is preventing it from working.
I had to devise a hack by having a .BAT which continuously overwrites default.uae in order to "prevent" this and use some customized settings.

However I discovered while writing this issue that my sole problem, in fact, was coming from a colon:
Could you tell me, in your startup-sequence, what is the purpose/usefulness of the colon in front of germz.exe:
cd dh1:
**:germz.exe**

This was thwarting my attempts to hook the debugger when booting from a floppy or a CD: 
now that I've found this, I simply added a colon in my startup-sequence too, so now it works wonderfully.

**Comment by BartmanAbyss** [comment]
Yeah, without the colon it wouldn't load. I have forgotten most of AmigaDOS's quirks, but I think it's an abbreviation for 'root of the current drive'
