### ISSUE TITLE
bump release in store?

### ISSUE THREAD

**Issue by tehKaiN** [BartmanAbyss/vscode-amiga-debug#17]
Since changes so far seem to be stable, perhaps it's time to update extension in vscode marketplace? This is mainly for #7 because it's needed to set up CMake workflow correctly, which my library extensively use, and I have some ppl asking me when my project will be compatible with your extension. ;)

**Comment by BartmanAbyss** [comment]
I have to finish up the gfx debugger before I release the next version to the marketplace. So it‘ll probably be a couple more weeks.

**Comment by BartmanAbyss** [comment]
Oops.. added too much new features. Marketplace update coming very soon ;)

**Comment by nj-designs** [comment]
Sorry to bump this. Any near term plan to update the market place version?

Thanks...

**Comment by tehKaiN** [comment]
@BartmanAbyss I know that you're busy with your plugin seminar, but perhaps it's good idea to update the plugin in marketplace before doing the talk - some ppl will definitely want to try it and will end up using the ancient version.
