### ISSUE TITLE
Getting a HALT3 using the "A4000" config

### ISSUE THREAD

**Issue by donorman** [BartmanAbyss/vscode-amiga-debug#19]
The a500 and a1200 configs works out of the box with added-rom files, 
cannot get the a4000 config to work though, got a HALT3 error and a black screen only.  

Also kind of expected to be able to fire up a "1260", poking around in amigaDebug.js using
config['quickstart'] = 'a1200,4';  instead of config['quickstart'] = 'a1200,0';  
and adding:
config['cpuboard_rom_file']= <Blizzard_1260.rom>
config['cpuboard_rom_file_id']='F88AE0F1,Blizzard 1240/1260'
Did not work either, got a black screen and a HALT3. 
[edit] Using "winuae64.exe -portable" instead of "winuae-gdb -portable" with the generated default.uae works though :-) 

I highly appreciate your effort making this!

**Comment by BartmanAbyss** [comment]
Can reproduce here. Will have a look at it later.

**Comment by BartmanAbyss** [comment]
You can have a look at the latest preview release for a fix.
