### ISSUE TITLE
stdio.h: No such file or directory  #include <stdio.h>

### ISSUE THREAD

**Issue by terriblefire** [BartmanAbyss/vscode-amiga-debug#2]
I'm pretty sure i would work round this issue but I wanted to give you feedback on a clean machine running the project for the first time. 

Perhaps some hard coded path in there somwhere that needs updated?
```

> Executing task: c:\Users\stephen\.vscode\extensions\bartman-abyss.amiga-debug-0.7.0\bin\gnumake.exe -f Makefile8mingw -j4 <

Makefile8mingw:41: target 'obj8mingw/main.o' given more than once in the same rule
Compiling bin/elf2hunk.c
C:/github/vscode-amiga-debug/bin/elf2hunk.c:10:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
gnumake: *** [Makefile8mingw:44: obj8mingw/elf2hunk.o] Error 1
The terminal process terminated with exit code: 1
```

I wonder if this is only triggered due to the modification date on a clean checkout?

**Comment by BartmanAbyss** [comment]
Hmm.. what did you do? There's no need to compile `elf2hunk.c`. That's coming from within the extension. I think your project folder isn't set up right.

**Comment by BartmanAbyss** [comment]
OTOH, there may be some new bug here.. Hold on, I'm taking a look...

**Comment by terriblefire** [comment]
i'll wipe the folder and checkout again. Just to be sure.

**Comment by terriblefire** [comment]
with a clean checkout. 
1. Launch VS Code. 
2. Open the folder. 
3. Run Amiga: Init Amiga Project
4. Press F5

I see the error above. 

I skipped the kickstart step this time to reduce the reproduction steps. It wouldnt make a difference until runtime though correct?

**Comment by BartmanAbyss** [comment]
something broke with the latest VS Code update. Trying to fix...

**Comment by terriblefire** [comment]
No worries. :) Thanks

**Comment by BartmanAbyss** [comment]
Hmm.. seems I was just seeing a problem running a development build of the extension.
When I ran the installed extension, everything was working fine.. Can you make sure your project folder is empty and try "Init Amiga Project" again? Also, by any chance did your project folder path contain any spaces?

**Comment by BartmanAbyss** [comment]
See [here](https://www.twitch.tv/videos/468413972?t=02h31m31s) how it's supposed to work...

**Comment by terriblefire** [comment]
Ok i got it. The unintuitive bit is not your fault. its how the Amiga-Assembly project worked. 

Basically i ran Init Amiga Project in the git checkout folder. I can see this isnt correct but I can also see other users making the same mistake. May want to think about how to avoid getting asked this dumb question over and over.

**Comment by BartmanAbyss** [comment]
Cool! Any idea how I could clarify it in the README?

**Comment by BartmanAbyss** [comment]
I think I could add a check for "Init Amiga Project" to make sure the folder is empty...

**Comment by terriblefire** [comment]
Yeah. that would save you some headaches methinks.

**Comment by BartmanAbyss** [comment]
done. 0.7.1 uploaded
