### ISSUE TITLE
Move kickstart ROM paths to vscode settings

### ISSUE THREAD

**Issue by tehKaiN** [BartmanAbyss/vscode-amiga-debug#20]
Hi,

I've started developing a project along with a friend. Everything works nice, except that we have kickstart ROMs in totally different filesystem paths. I know that we can just unify that on our side, but I think that it would be more beneficial to have it predefined globally for whole extension. This way the launch.json won't change and could be commited on repository and used by anyone without any changes.

There are two ways in which it could be solved:

- in settings.json add "path to kickstart" and use it as a var in launch.json paths, like `"kickstart": "${amiga.kickstartPath}/kick13.rom",`. It would still require filenames to be exactly the same, but it's still better than current approach.
- in settings.json add `amiga.kickstarts` object which could be assigned with `"name": "filePath"`, like:

```json
"amiga.kickstarts": {
  "kick13": "/path/to/my/kick13.rom",
  "kick30": "/path/to/my/kick30dumpedFromMyAmiga.bin"
}
```

Dunno which approach is better. This is a low priority issue for me. ;)

**Comment by nyteshade** [comment]
I modified the files in the extension directory so they persist but yes, this is a usability issue I'd like to see corrected as well.

**Comment by BartmanAbyss** [comment]
#117
