### ISSUE TITLE
WINUAE: Debugging only works if using AROS replacement Rom.

### ISSUE THREAD

**Issue by AdamENESS** [BartmanAbyss/vscode-amiga-debug#201]
Kind of got a strange one here.
I can't debug my game or even the demo if I use any rom other than the inbuilt winuae AROS Rom.
Otherwise Winuae Locks up as the debugger is trying to connect to it. Just as the executable is loading.

No idea Why, worked on my Old laptop, but on my new one I get lockups.
Both of them are running Windows 11, so It can't be that.

@tehKaiN doesn't have this issue, we were chatting on discord, and I even tried to replicate his setup for cmake etc. (Using his ACE code base)

He even tested my project on his PC and it debugged fine.

**Comment by BartmanAbyss** [comment]
Are you by any chance using encrypted kickstarts (Cloanto)? Maybe it's related to #199

**Comment by AdamENESS** [comment]
I grabbed the roms from my A500 Mini, and it works now, so it was either something to do with the roms I had, which are from Cloanto, or where they were stored on my HD.

Only strange part was that my OLD laptop used cloanto too.

At least I can debug again woo.

**Comment by AdamENESS** [comment]
Yep, it was the romset I used.  They seem to be 1kb bigger than the standard roms.
