### ISSUE TITLE
FS-UAE warp launch?

### ISSUE THREAD

**Issue by torkildl** [BartmanAbyss/vscode-amiga-debug#205]
I noticed that WinUAE has a warp launch (which I think is skipping hw tests). Would it be possible to get that option also for FS-UAE? It would be very useful oæif it speeds up the debugger startup.

**Comment by grahambates** [comment]
FS-UAE does (should!) already start in warp mode aka fast-forward, which gets disabled when the Amiga program starts. To confirm that this is working for you, should see this overlay when it's starts up.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/1519709/215053622-15c7a156-fe61-4cad-aab3-509f5676dfeb.png">

AFAIK this doesn't skip anything, it just runs fast than realtime. If there's another setting in WinUAE that skips hardware checks that would definitely be worth looking at. Do you have any references for this as I haven't been able to find anything?

**Comment by torkildl** [comment]
I had the impression that Warp-launch in WinUAE was about the boot sequence ("turbo boot"), and not the emulator speed.  My only reference is this, from the README:
![image](https://user-images.githubusercontent.com/9461154/215057349-4795aab6-ca72-47dc-a32a-4efe96765492.png)

**Comment by grahambates** [comment]
@BartmanAbyss is this a separate feature or is it just referring to starting in warp mode? I don't see any reference to it outside of this project.

**Comment by grahambates** [comment]
@torkildl are you getting noticably slow startup times? On an A1200 config I get <2 secs delay from FS-UAE opening to the program running. For A500 it's more like 6 secs.

**Comment by BartmanAbyss** [comment]
Yeah, this is just referring to the starting in warp-mode.

**Comment by grahambates** [comment]
One possible tip for quicker iteration is that if you're just running your program and not using the debugger, you don't have to restart the emulator each time. If your program quits back to CLI you can just run it again, having updated the exe.

**Comment by torkildl** [comment]
I get about 6sec on A500. These are good tips! But would it at all be possible to patch the emulator in a way that increases startup speed?

**Comment by grahambates** [comment]
Yeah all for it if there are any ideas! To be clear though, starting in warp mode already improves matters considerably and this is really more of a feature request for FS-UAE / WinUAE, and not really specific to this extension. The remote debugger connecting doesn't really add noticable delay in addition to the normal startup time in my experience.

All that being said, one idea that comes to mind is snapshots. Perhaps the emulator could start with a snapshot of the state right before the program runs.

**Comment by BartmanAbyss** [comment]
> All that being said, one idea that comes to mind is snapshots. Perhaps the emulator could start with a snapshot of the state right before the program runs.

I'm not sure that would work. Need to get the current filesystem and all.
Maybe your PC is just too slow? A faster PC speeds up startup time. I think I change all accuracy settings during bootup to be as relaxed and fast as possible.

**Comment by BartmanAbyss** [comment]
Are you using AROS or Kickstart? There seems to be a difference in start-up time.
Anyways, for reference here are the startup times for my Windows 11, Ryzen 5950X machine:
https://user-images.githubusercontent.com/19374186/215106704-a6110705-6046-42fe-8301-d14466d11189.mp4

**Comment by grahambates** [comment]
To be fair that's a bit quicker than what I see on Mac and I'd suspect that one reason is that FS-UAE has limited options for accuracy so doesn't benefit from the optimisation you mentioned. I tend to use A1200 config for fast iteration.

**Comment by torkildl** [comment]
I have noticed that kickstart is preferable, but I think the startup time still could be improved. Agree it is an FS-UAE/winUAE-issue and I will open an issue on the FS-UAE repo.

**Comment by emoon** [comment]
What I did a while ago was to modify FS-UAE so it would boot start with warp mode enable and then from code I would disable to warp mode (so I added a hook inside the emulator that I could call from the emulated code) that way I would get the fastest boot speed, program loading, etc and run directly at normal speed at a specific point in my program.

**Comment by BartmanAbyss** [comment]
That's exactly the same thing I did ;)
