### ISSUE TITLE
update FS-UAE and merge aga colors patch

### ISSUE THREAD

**Issue by BartmanAbyss** [BartmanAbyss/vscode-amiga-debug#206]
Hi @grahambates , I just updated WinUAE to the latest commit (which changes dma_rec struct as well as other things) https://github.com/tonioni/WinUAE/commit/239062dc7c49838b41ac54e5901522eeb78f0ef0
and now write out aga colors in .profile files
https://github.com/BartmanAbyss/WinUAE/commit/fb62035ea0da29b62baf91c407d2ca62d280812e
These changes make existing .profile files incompatible.
could you merge these changes in your FS-UAE fork?

**Comment by grahambates** [comment]
Yeah, no problem
