### ISSUE TITLE
Profiler: Windows AppData/Local/Temp cleanup job

### ISSUE THREAD

**Issue by ReneKriest** [BartmanAbyss/vscode-amiga-debug#210]
Generating a profile (*.amigaprofile) leads to the build-up of a data file, that is, in my case, at least 5MB in size. Size varies between 5 and 11MB.

These files get stored in appdata/local/temp however there is no clean-up job. This can lead to cluttering hard disk space.

I would really like to see a corn job or, preferred, button to clean up old profile files.

**Comment by BartmanAbyss** [comment]
In the command palette, use `Amiga: Clean Temp Files`
