### ISSUE TITLE
Unable to use amigalib.

### ISSUE THREAD

**Issue by m1awicki** [BartmanAbyss/vscode-amiga-debug#212]
Hi,
it seems that it is not possible to use Amiga lib. After including `proto/alib.h`  lots of compilation errors appear due to missing `__stdargs.` Adding `#define __stdargs` solves the compilation problem but then program fails to link due to missing symbols.

In order to reproduce the problem simply add `#include <proto/alib.h>` to `main.c` in demo project included with VSCode exstension.

Example compilation error (fragment):
```
.vscode\extensions\bartmanabyss.amiga-debug-1.7.1\bin\win32\opt\m68k-amiga-elf\sys-include\clib\alib_protos.h:58:1: error: unknown type name '__stdargs'
   58 | __stdargs APTR LibAllocPooled( APTR poolHeader, ULONG memSize );
```

Linker error:
```
.vscode/extensions/bartmanabyss.amiga-debug-1.7.1/bin/win32/opt/bin/../lib/gcc/m68k-amiga-elf/12.2.0/../../../../m68k-amiga-elf/bin/ld.exe: obj/main.o: in function `main':
F:/Amiga/Development/repos/abyss_demo/main.c:369: undefined reference to `CreateExtIO'
collect2.exe: error: ld returned 1 exit status
gnumake: *** [Makefile:50: out/a.elf] Error 1
```

**Comment by BartmanAbyss** [comment]
Sorry, Amiga.lib is not included

**Comment by m1awicki** [comment]
Are there any chances for this to change?

**Comment by BartmanAbyss** [comment]
Probably not unless there are sources of Amiga.lib available. This gcc branch operates on ELF files, not Amiga Hunk files b

**Comment by m1awicki** [comment]
Thank you for quick reply. I am closing the issue.
