### ISSUE TITLE
Compiling -O0 with 1.1.0 preview

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#22]
One new issue I've run into with the 1.1.0 preview is that if I change the makefile so it'll compile with -O0 for easier debugging then it'll give me compile error in the support code around memcopy and memset. I can fix it by commenting out the special optimization options those functions have but that didn't use to be necessary.

**Comment by BartmanAbyss** [comment]
Yeah, it seems O0 is not working, but we had good experience with Og.
The Compiler shouldn‘t have changed between 1.0 and 1.1...
