### ISSUE TITLE
Add floppy or hard drive to emulator while debugging

### ISSUE THREAD

**Issue by rb-anssi** [BartmanAbyss/vscode-amiga-debug#220]
Hi,

First of all great work for this extension!

I wondered if there was a way to add a floppy `adf` or hard disk drive file in the emulator configuration so that a program reading them could be debugged (note : i am under Linux, hence using `fs-uae` behind the scene).

Thanks in advance for the help!

**Comment by BartmanAbyss** [comment]
>Extension automatically mounts executable's directory as `dh1:`, allowing for reading and writing files.
would that work for you?

**Comment by rb-anssi** [comment]
Thanks @BartmanAbyss for the hint, sorry I missed that in the documentation!
