### ISSUE TITLE
any chance of getting stdlib?

### ISSUE THREAD

**Issue by sacredbanana** [BartmanAbyss/vscode-amiga-debug#223]
I'm trying to write an app but unable to use either socket.h or bsdsocket.h because they require stdlib.h. Would it be possible to add this?

**Comment by BartmanAbyss** [comment]
You can try to just copy it from the official gcc/libc into your directory and adjust it to your needs.

**Comment by sacredbanana** [comment]
Hmm I can't even use the included bsdsocket.h because it's saying __asm is undefined

**Comment by BartmanAbyss** [comment]
You have to make sure it includes the `inline/` version, not the `pragmas/` or the `defines/` version (compare https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/bin/win32/opt/m68k-amiga-elf/sys-include/proto/exec.h)
