### ISSUE TITLE
Resource bitmap colors are inverted.

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#226]
Something happens and now the colors for resources are incorrect.

The copper palette resources, copper disassembly and screen views are all using the correct colors but the resource bitmaps are all flipping red and blue as far as I can tell.

In this image the logo should be orange/yellow as per the copper list:
![image](https://user-images.githubusercontent.com/5326134/231304826-773cdfab-4eb3-463e-b506-fff5ebbae731.png)

**Comment by BartmanAbyss** [comment]
sorry for delay 😅
