### ISSUE TITLE
Could the debug text font be changed?

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#227]
Could the debug text font be changed to something a little more plain?
I find it isn't always the most readable, mostly the numbers are sometimes not so easy to read.

![image](https://user-images.githubusercontent.com/5326134/231326008-3151dafd-b88d-47f9-8f04-31a7641a5fb7.png)

**Comment by BartmanAbyss** [comment]
if you can provide topaz.font as pixel data like [this](https://github.com/BartmanAbyss/WinUAE/blob/master/debug.cpp#L1630), I can add it.

**Comment by rjobling** [comment]
I was going to try fixing it myself but getting Winuae to compile seems like an ordeal, so sorry but this should do it:

https://github.com/rjobling/snippets/blob/a69766c569310eca436361cf90394bb89c725d3c/barto_font.c

**Comment by BartmanAbyss** [comment]
Thanks for the font.  I will include it in the next release. You can get a new winuae-gdb.exe from the repo in the meantime.
