### ISSUE TITLE
'index' is not a constant expression when changing main.c to main.cpp

### ISSUE THREAD

**Issue by nattrass** [BartmanAbyss/vscode-amiga-debug#231]
The readme states that if we want to use c++ it's just a case of renaming the main.c to main.cpp. 

But when I do this I get the following error on line 262 for the following function during compilation. 

'index' is not a constant expression

```
__attribute__((always_inline)) inline USHORT* copSetColor(USHORT* copListCurrent, USHORT index,USHORT color) {
	*copListCurrent++=offsetof(struct Custom, color[index]);
	*copListCurrent++=color;
	return copListCurrent;
}
```

**Comment by BartmanAbyss** [comment]
Thanks for noticing. Seems to have changed when gcc was updated. I have fixed it for C++. You can grab the new `main.c` here until I release a new version: https://github.com/BartmanAbyss/vscode-amiga-debug/commit/6d815baea3da14673e1a5af70d9505b3c3905563
