### ISSUE TITLE
macOS/FS-UAE: Error: the description can't be converted into a problem matcher

### ISSUE THREAD

**Issue by DidierMalenfant** [BartmanAbyss/vscode-amiga-debug#233]
When running the sample project, Everything compiles and executes fine but I get this as an output:
```
Error: the description can't be converted into a problem matcher:
{
    "base": "$gcc",
    "fileLocation": "absolute"
}
```

**Comment by DidierMalenfant** [comment]
I did but I had disabled it like an idiot while doing something unrelated. My bad!

Thank you!

**Comment by basiq-ndjordjevic** [comment]
Hi, I can't find what other recommended C++ extensions need to be installed?
Thanks.

**Comment by BartmanAbyss** [comment]
just go to your extensions tab, in the bottom there will be a list of recommended extensions. look for those that say "because you have Amiga... installed"
