### ISSUE TITLE
MacOS : fatal error: cannot execute 'cc1': execvp: No such file or directory

### ISSUE THREAD

**Issue by BastianZuehlke** [BartmanAbyss/vscode-amiga-debug#236]
Ventura - VS Code 1.82.0 - v1.7.3 
Creating Default Test Project, no changes.

Compiling main.c
Compiling support/gcc8_c_support.c
Assembling support/gcc8_a_support.s
m68k-amiga-elf-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.

**Comment by BartmanAbyss** [comment]
Hmm.. can you try with 1.7.2? Does it work?

**Comment by BastianZuehlke** [comment]
It was the permission issue.It seems I need to add +x to nearly all files.

However, now I get 

Compiling main.c
Compiling support/gcc8_c_support.c
Assembling support/gcc8_a_support.s
Assembling support/depacker_doynax.s
Assembling support/depacker_doynax_vasm.asm
Assembler messages:
Fatal error: can't create obj/gcc8_a_support.o: No such file or directory
make: *** [obj/gcc8_a_support.o] Error 1
make: *** Waiting for unfinished jobs....
Assembler messages:
Fatal error: can't create obj/depacker_doynax.o: No such file or directory
make: *** [obj/depacker_doynax.o] Error 1
/Users/bastianzuhlke/Development/tmp/test/main.c:506:1: fatal error: opening dependency file obj/main.d: No such file or directory
  506 | }
      | ^
compilation terminated.
make: *** [obj/main.o] Error 1
/Users/bastianzuhlke/Development/tmp/test/support/gcc8_c_support.c:289:1: fatal error: opening dependency file obj/gcc8_c_support.d: No such file or directory
  289 | }
      | ^
compilation terminated.
make: *** [obj/gcc8_c_support.o] Error 1

**Comment by BastianZuehlke** [comment]
Ok after creating obj and out directory manually it works.

**Comment by BartmanAbyss** [comment]
my bad. forgot to update the version number in a source file. will post a new version asap.

**Comment by BartmanAbyss** [comment]
fixed in https://github.com/BartmanAbyss/vscode-amiga-debug/commit/67b71f5a909636ab17681c912686ce548de18aec

**Comment by TheJare** [comment]
I just installed v1.7.4 of the extension on my Windows machine and got the same problem, I had to create the out and obj folders manually.

**Comment by laurencedobson** [comment]
Likewise, I installed and also had to create the `bin/` and `out/` folders in the workspace root
