### ISSUE TITLE
settings.json wrong?

### ISSUE THREAD

**Issue by MihaMarkic** [BartmanAbyss/vscode-amiga-debug#238]
Hi, on Windows 10 when I init project, I get this (commented out) instead of (I guess) uncomented line in settings.json file:
```
"m68k.includePaths": [
        //"c:\\Users\\bwodok\\Documents\\Visual_Studio_Code\\vscode-amiga-debug\\bin\\win32\\opt\\m68k-amiga-elf\\sys-include"
		"C:\\Users\\[USER]\\.vscode\\extensions\\bartmanabyss.amiga-debug-1.7.4\\bin\\win32\\opt\\m68k-amiga-elf\\sys-include"
	],
```

I guess that is wrong?

**Comment by BartmanAbyss** [comment]
Yeah, I shouldn't have included that file in the release, but it gets overwritten by the extension anyways with correct values, so it shouldn't be a problem.

**Comment by TheJare** [comment]
It self-corrected as you said, however I was quite confused for a while by intellisense errors: to get intellisense to find those includes in `main.c`, I still had to close/reopen the project in vscode.
