### ISSUE TITLE
gcc8_a_support missing on new project

### ISSUE THREAD

**Issue by pmprog** [BartmanAbyss/vscode-amiga-debug#241]
Hi,

 I've just installed 1.7.4 on VSCodium (and also via the MarketPlace on a brand new fresh VSCode install), and followed the instructions to create a new empty folder, and use the Init Project in it, but when I press `F5` to run it, it gets a build error regarding gcc8_a_support.

 Running Windows 10.

 Any ideas? Thanks

```
Compiling main.c
Compiling support/gcc8_c_support.c 
Assembling support/gcc8_a_support.s
Assembling support/depacker_doynax.s
Assembler messages:
Fatal error: can't create obj/gcc8_a_support.o: No such file or directory
D:/AmigaDev/SackTheTower/main.c:506:1: fatal error: opening dependency file obj/main.d: No such file or directory
  506 | }
      | ^
compilation terminated.
D:/AmigaDev/SackTheTower/support/gcc8_c_support.c:289:1: fatal error: opening dependency file obj/gcc8_c_support.d: No such file or directory
  289 | }
      | ^
compilation terminated.
gnumake: *** [Makefile:69: obj/main.o] Error 1
gnumake: *** Waiting for unfinished jobs....
gnumake: *** [Makefile:69: obj/gcc8_c_support.o] Error 1
gnumake: *** [Makefile:73: obj/gcc8_a_support.o] Error 1
```

**Comment by BartmanAbyss** [comment]
The current version is missing ‚obj‘ and ‚out‘ directories in the template project. Just create these 2 directories within your project and it should work.

**Comment by pmprog** [comment]
Thank you

**Comment by BartmanAbyss** [comment]
fixed in https://github.com/BartmanAbyss/vscode-amiga-debug/releases/tag/1.7.5
