### ISSUE TITLE
CloseWorkBench() is unable to close workbench screen

### ISSUE THREAD

**Issue by sacredbanana** [BartmanAbyss/vscode-amiga-debug#25]
Hi

I have an issue where the system call CloseWorkBench() fails. This call is used to close the main workbench screen. I do this to free up some memory. This normally only fails if some non drawer windows are open but none are. I assume something hidden is preventing the workbench screen to close?

**Comment by BartmanAbyss** [comment]
Hi,
maybe this has something to do with the default shell window? The program being debugged is run from the startup-sequence without [`RUN`](https://wiki.amigaos.net/wiki/AmigaOS_Manual:_AmigaDOS_Command_Reference#RUN), so probably it can't close the workbench screen because the CLI window is still open.
Can you try modifying `c:\Users\[YourUserName]\.vscode\extensions\bartmanabyss.amiga-debug-1.0.0\bin\dh0\s\startup-sequence` and replace `:runme.exe` with `run :runme.exe`?

**Comment by sacredbanana** [comment]
![image](https://user-images.githubusercontent.com/6903516/89199144-b9834580-d5e0-11ea-9dbd-b7ba83aed47a.png)

**Comment by BartmanAbyss** [comment]
aha, so the amiga wiki lied ;) Get a Workbench 1.3 disk, make a new directory `c:\Users\[YourUserName]\.vscode\extensions\bartmanabyss.amiga-debug-1.0.0\bin\dh0\c` and copy RUN from the C directory on the WB disk there.

**Comment by sacredbanana** [comment]
OK I copied the run utility over (I was planning on trying that anyway) and now I get this:
![image](https://user-images.githubusercontent.com/6903516/89200530-bc7f3580-d5e2-11ea-80b4-5a3dab561f82.png)

**Comment by sacredbanana** [comment]
I inserted a new line after that line and it gets rid of the y with 2 dots but its still the same unknown command

**Comment by BartmanAbyss** [comment]
hmm... strange... can you pack up a small repro case of your project? I'll take a look.

**Comment by sacredbanana** [comment]
Invite sent to my private repo

**Comment by sacredbanana** [comment]
If I remove the : to make it just run runme.exe it executes but still doesnt close the screen

**Comment by BartmanAbyss** [comment]
So, I found the correct startup-sequence by searching through old games, and found it in 'The Settlers':
```
run >nil: <nil: runme.exe >nil: <nil:
endcli >nil:
```
Copy the EndCLI command from the Workbench disk (same location as Run)

Also, for further information, check http://amigadev.elowar.com/read/ADCD_2.1/Libraries_Manual_guide/node0576.html

I'll think about how I go on including that feature in future versions.

**Comment by sacredbanana** [comment]
No luck so far. I tried your solution and I get this:

![image](https://user-images.githubusercontent.com/6903516/89299797-cd3eb280-d699-11ea-946b-bf9c78e3ec85.png)

**Comment by BartmanAbyss** [comment]
Hmm I tried the solution above and it did work for me. I'm not sure what's going wrong here...

**Comment by sacredbanana** [comment]
I thought nil: was always available as a system device

**Comment by sacredbanana** [comment]
Could it be a difference between the vscode marketplace version of the extension and what is on the latest commit?

**Comment by BartmanAbyss** [comment]
Yes, there's differences, however I don't think any of the changes affect this issue.

**Comment by BartmanAbyss** [comment]
I couldn't get it to work with the 1.0 release, so I added the new configuration parameter `endcli` to `.vscode/launch.json`. Get the [latest preview](https://github.com/BartmanAbyss/vscode-amiga-debug/releases/tag/1.1.0-preview24) and be sure to read the `CHANGELOG` (there have been some configuration changes), then in `.vscode/launch.json`, below the `"program": ...` line, add `"endcli": true,` and it should work!

**Comment by sacredbanana** [comment]
It worked! You sir are a hero

**Comment by sacredbanana** [comment]
Just tested on Kickstart 3.1.4 and the issue is present with this KS still. Probably affects KS > 2.0 ?
