### ISSUE TITLE
Trouble using 1.7.6 on MacOS Sonoma

### ISSUE THREAD

**Issue by bubbob42** [BartmanAbyss/vscode-amiga-debug#250]
Hi!

I'm getting the following error with Sonoma, both during installation of the plugin and when trying to build via F5:

`Error: the description can't be converted into a problem matcher:
{
    "base": "$gcc",
    "fileLocation": "absolute"
}

Error: the description can't be converted into a problem matcher:
{
    "base": "$gcc",
    "fileLocation": "absolute"
}`

**Comment by BartmanAbyss** [comment]
Hi, I think you need to install the optional C++ extension. See your extensions tab in VSCode. This should bring the $gcc problem matcher

**Comment by bubbob42** [comment]
Thanks for your swift reply! I indeed installed the C++ extension, but only after installing your extension. :)

So what I had to do was:
- uninstall amiga-debug
- reinstall

and now it works, thanks!

(I suggest modifying the installation readme, adding a note to install the C++ extensions, first)

**Comment by BartmanAbyss** [comment]
The order shouldn't matter. But yes, the C++ extension was recently changed from required to recommended, so I will update the README accordingly.
