### ISSUE TITLE
Appcrash: WinUAE has stopped working (winuae-gdb.exe 4.4.0.0) [KS 1.3]

### ISSUE THREAD

**Issue by jbilander** [BartmanAbyss/vscode-amiga-debug#28]
Hello, thanks for this awesome project. I've just tried it out with a fresh install from marketplace `(v1.0.0)` and wrote a simple helloworld program. It works as expected but `winuae-gdb.exe` crashes after a while, sometimes after 15 seconds and sometimes a little later, a little random when it occurs but seem to always happen. It is highly reproducible. This is when running on `A500 KS 1.3 (kick34005.A500)` rom with or without debugging. If I close the winuae window by clicking [x] it freezes and hangs. Trying the same on `A1200 KS 3.1 (kick40068.A1200)` or `KS 2.0 (kick37175.A500)` works fine without any crashes and doesn't hang. I'm using a `win 8.1` machine and latest `VSCode 1.47.3 64-bit`. The crash seems to be caused by different dll calls e.g. to `ntdll.dll`, details below, any clue what is causing this? Tried on KS 1.2 too and same problem there so problem seems to be tied to when using older Kickstarts.

    Problem signature:
      Problem Event Name:	        APPCRASH
      Application Name:	        winuae-gdb.exe
      Application Version:	        4.4.0.0
      Application Timestamp:	5ed1714a
      Fault Module Name:	        ntdll.dll
      Fault Module Version:	        6.3.9600.19678
      Fault Module Timestamp:	5e82c88a
      Exception Code:	        c0000005
      Exception Offset:	        00000000000358fa
      OS Version:	                6.3.9600.2.0.0.256.48
      Locale ID:	                1053
      Additional Information 1:	cee4
      Additional Information 2:	cee49baf695955cc06ce73bf396842b0
      Additional Information 3:	ac31
      Additional Information 4:	ac31d5743764a6b1b96c6fe1859d6916

    Problem signature:
      Problem Event Name:	        APPCRASH
      Application Name:	        winuae-gdb.exe
      Application Version:	        4.4.0.0
      Application Timestamp:	5ed1714a
      Fault Module Name:	        StackHash_2269
      Fault Module Version:	        6.3.9600.19678
      Fault Module Timestamp:	5e82c88a
      Exception Code:	        c0000374
      Exception Offset:	        PCH_C3_FROM_ntdll+0x0000000000090CBA
      OS Version:	                6.3.9600.2.0.0.256.48
      Locale ID:	                1053
      Additional Information 1:	2269
      Additional Information 2:	2269d2f9a7df7b894866693deedbe695
      Additional Information 3:	2387
      Additional Information 4:	238760144906e0a39667ea3de5604a11

    Problem signature:
      Problem Event Name:	        APPCRASH
      Application Name:	        winuae-gdb.exe
      Application Version:	        4.4.0.0
      Application Timestamp:	5ed1714a
      Fault Module Name:	        GDI32.dll
      Fault Module Version:	        6.3.9600.19781
      Fault Module Timestamp:	5f0d29d8
      Exception Code:	        c0000005
      Exception Offset:	        000000000000972c
      OS Version:	                6.3.9600.2.0.0.256.48
      Locale ID:	                1053
      Additional Information 1:	e6da
      Additional Information 2:	e6dad71e24846c6e936596e26d8739b2
      Additional Information 3:	23c4
      Additional Information 4:	23c498ae9be98440f541d454c625566d

<a href="https://imgur.com/xlZf5Yb.jpg">
<img src="https://imgur.com/xlZf5Ybs.jpg">
</a>
<a href="https://imgur.com/tLfVvJ8.jpg">
<img src="https://imgur.com/tLfVvJ8s.jpg">
</a>
<a href="https://i.imgur.com/bOzWo0B.jpg">
<img src="https://imgur.com/bOzWo0Bs.jpg">
</a>

**Comment by BartmanAbyss** [comment]
Thanks for using my extension.
Yeah, try not to exit your test program. Seems that's not handled by the debugger. It probably thinks the program's still running.

**Comment by jbilander** [comment]
Ah, thanks! That worked better.
