### ISSUE TITLE
Feature: OS Support

### ISSUE THREAD

**Issue by Real-MJoe** [BartmanAbyss/vscode-amiga-debug#29]
Hello,

is it possible to run the cool extension under OS? You could exchange WinUAE with FS-UAE. 

Greetings

**Comment by BartmanAbyss** [comment]
Hi, unfortunately it's not possible. I added custom debugging features to WinUAE.

**Comment by Real-MJoe** [comment]
That's a pity to read. For the amiga-assembly extention FS-UAE has been "opened" in certain points for better debugging. 
But you are the boss.

**Comment by nekoniaow** [comment]
@BartmanAbyss is there any hope for your changes to be eventually merged back in the main UAE branch?

Also, I could give a try merging your changes to FS-UAE, how much work do you think this would represent?
