### ISSUE TITLE
__attribute__((aligned(n)) doesn't seem to work for static vars.

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#33]
Hi Bartman
Loving this system and the profiler and all the updates! But wanted to ask if you are aware of a way to force alignment for static variables. Using  `__attribute__((aligned(n))` works fine for structs but in my case I'm just trying to align a statically allocated array.

**Comment by BartmanAbyss** [comment]
What exactly are you trying to do? Care to post a small code snippet?

**Comment by rjobling** [comment]
Try using this code instead of the main.c in the sample, it demonstrates an attempt to declare some aligned static variables. As you can hopefully see the size alignment for the struct has worked. But the static allocation alignment has not worked. Worse if you attempt to align larger than 512 then it no longer is able to run. I think it has maybe failed to link and there is no error message for that.

`#include "support/gcc8_c_support.h"
#include <proto/exec.h>
#include <proto/dos.h>

struct ExecBase *SysBase;
struct DosLibrary *DOSBase;

struct Test
{
	int a, b;
} __attribute__((aligned(16)));

static struct Test test1;
static struct Test test2 __attribute__((aligned(256)));
static int buffer[1024] __attribute__((aligned(512)));

int main()
{
	SysBase = *((struct ExecBase**)4UL);
	DOSBase = (struct DosLibrary*)OpenLibrary((CONST_STRPTR)"dos.library", 0);
	if (!DOSBase)
		Exit(0);

	test1.a = 1;
	test1.b = 2;
	test2.a = 3;
	test2.b = 4;

	for (int i = 0; i < 1024; i++)
	{
		buffer[i] = test1.a + test1.b + test2.a + test2.b + i * i;
	}

	KPrintF("test1 address:%lx", &test1);
	KPrintF("test2 address:%lx", &test2);
	KPrintF("buffer address:%lx", buffer);

	KPrintF("test1 size:%ld", sizeof(test1));
	KPrintF("test2 size:%ld", sizeof(test2));
	KPrintF("buffer size:%ld", sizeof(buffer));

	while (1)
	{
	}
}
`

**Comment by rjobling** [comment]
This is the output I get:
```

test1 address:C0E1E8
test2 address:C0E1D8
buffer address:C0D1D8
test1 size:16
test2 size:16
buffer size:4096

```

**Comment by BartmanAbyss** [comment]
yeah, I don't think you can do alignment greater than 4 bytes. I'm pretty sure the Amiga hunkloader doesn't support that.

**Comment by rjobling** [comment]
Thanks
