### ISSUE TITLE
Code debug break points

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#34]
Hi Bartman
Is there a way to code a debug break point in C or inline asm? I thought maybe calling the exec function Debug(0) would do it. That seems to be an old way to hook into debuggers. How does the framework trigger break points? Maybe I can just emit the correct magic code?

**Comment by BartmanAbyss** [comment]
Hmm.. GDB needs to set breakpoints. The emulated Amiga knows nothing about breakpoints.

**Comment by rjobling** [comment]
What about a reliable way of crashing the emulation that the debugger would catch? I'm just trying to put together a useful assert macro.

**Comment by BartmanAbyss** [comment]
Yeah sure, you can do that. We're just doing an infinite loop and hit the pause button. The debugger breaks on address error (unaligned access, needs to be generated via inline asm) and "TRAP#7" opcode.

**Comment by rjobling** [comment]
Thanks I used an unaligned write and that does the trick.
