### ISSUE TITLE
Laggy P61 module playback on A1200 configuration

### ISSUE THREAD

**Issue by yanekk** [BartmanAbyss/vscode-amiga-debug#36]
Although not released yet, I checked the sound playback capability available on master branch. Everything works fine with A500 configuration (around 20-25% CPU), but switching to A1200 config with the same binary gives big lags and CPU on the level of 130-150%, with clicky sound and slowed down execution. 

In order to separate the problem, I reassembled P61 player example from original sources available on Aminet and it sounds exactly the same (I can provide the exe if needed). Surprisingly, running the same binary on vanilla A1200 WinUAE setup (although 4.3.0, which IMHO makes no difference) runs perfectly smooth, so I guess there's something in the WinUAE configuration that makes it laggy. I tried to adjust the settings to match the not lagging one using the WinUAE GUI, but cannot find the culprit.

I'm just wondering if the problem also appears on your setup. I'm running Windows 10, WinUAE 4.4.0 as attached to current version of the extension.

PS: great thanks for bringing back my memories and allow me to learn how machine of my childhood/adolescence works and can be programmed. You made easier to fulfil my nostalgic dream of programming an Amiga computer!

**Comment by BartmanAbyss** [comment]
Hi, sorry for the delay. Was on vacation ;)

Hmm.. I don't know when I last tested the sample project on A1200 config. Maybe your PC is too slow? My extension makes sure that 'cycle exact emulation' is always enabled, this is probably much more CPU-intensive than simple emulation. Can you try to toggle the cycle exact emulation while WinUAE (either your version or the included one) is running and see if it's making any difference?
