### ISSUE TITLE
stdlib.h missing?!

### ISSUE THREAD

**Issue by nyteshade** [BartmanAbyss/vscode-amiga-debug#37]
I am profoundly impressed with this extension and it will definitely lead to me writing more Amiga code this year and going forward. I desperately wish there was a version for macos but in the meantime I went to use `calloc` and found that I could not compile because `stdlib.h` could not be found.

Is it a setting or is simply not there?

**Comment by BartmanAbyss** [comment]
Hi, there's no support for the standard library, you have to use the AmigaOS functions like [AllocMem](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node0332.html), please see the included example (`Amiga: Init Project`) for reference.

**Comment by nyteshade** [comment]
Are there any plans for introducing the standard library bits? AllocMem, and AllocVec are a pain in comparison. If not, its okay, but it would sure be nice if they existed.

**Comment by BartmanAbyss** [comment]
Not at the moment, sorry.
