### ISSUE TITLE
Unable to open console.device

### ISSUE THREAD

**Issue by sacredbanana** [BartmanAbyss/vscode-amiga-debug#40]
Hello

I am unable to open console.device despite me following the steps in the reference manuals. I'm thinking it may be an issue with 
vscode-amiga-debug since I simply cannot see any issues with the code.

The window, port and IORequest all open up with no errors. It only fails when OpenDevice() is called on line 58.

Feel free to tell me my code is wrong but this is what is in the reference manual for KS 1.3.

My repo is at https://github.com/sacredbanana/DF0Engine

Thanks so much, I'm pulling my hair out trying to get console.device to open :(

Btw I also had to comment out the inclusion of the <rexx/storage.h> header file since that appears to be missing in your extension.

**Comment by BartmanAbyss** [comment]
Sorry, no clue. If you think this is a issue with my extension, copy your EXE file to another WinUAE's workbench or something and test there..

**Comment by sacredbanana** [comment]
Sorry. False alarm. The console device was in fact opening perfectly fine. OpenDevice() returns 0 if it succeeds and i had a dumb moment and reported a failure if it was zero
