### ISSUE TITLE
Uninstalling / Reinstalling

### ISSUE THREAD

**Issue by nyteshade** [BartmanAbyss/vscode-amiga-debug#41]
No matter what I do now, I cannot get the extension to reinstall. I played with the unreleased version, then ram into issues and tried to revert to the main version. 

I’ve tried removing it using the GUI. I’ve tried removing it from %userprofile%\.vscode\extensions and I’m out of ideas. What am I missing?

**Comment by BartmanAbyss** [comment]
Any more details? When testing here, we're installing/uninstalling different versions via the .vsix all the time.

**Comment by nyteshade** [comment]
Let me see here:

When performing the following steps:

1. Open Visual Studio Code to a new empty folder on the Desktop
  Version: 1.49.2 (user setup)
  Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
  Date: 2020-09-24T16:29:41.983Z
  Electron: 9.2.1
  Chrome: 83.0.4103.122
  Node.js: 12.14.1
  V8: 8.3.110.13-electron.0
  OS: Windows_NT x64 10.0.19041

2.  The extensions currently installed are:
  Amiga C/C++ Compile, Debug & Profile: 1.1.0-preview3.1
  C/C++: 1.0.1
  Kite Autocomplete for Python and JavaScript: 0.124.0
  OmniPascal - Open Preview: 0.18.0
  Papyrus: 2.23.0
  Remote - WSL: 0.44.5

3. Open the command palette and select Amiga: Init Project
  I get the following error message
  Command 'Amiga: Init Project' resulted in an error (command 'amiga.initProject' not found)

**Comment by nyteshade** [comment]
This was working perfectly before, but no matter of removing or reinstalling seems to get it to work any longer. So I'm looking for ideas on how to remedy that.

**Comment by BartmanAbyss** [comment]
Sorry, neither do I. Have you tried uninstalling VSCode and deleting all of its settings folders?

**Comment by nyteshade** [comment]
Reinstalling the editor seemed to have helped. Not sure what happened.
