### ISSUE TITLE
preview32 and preview31 do not compile the sample app out of the box

### ISSUE THREAD

**Issue by nyteshade** [BartmanAbyss/vscode-amiga-debug#46]
Both preview31 and preview32 do not compile and run the sample application generated by Amiga Init Project.

**Comment by BartmanAbyss** [comment]
can't reproduce here. Are you creating the project in a directory with spaces in the path name anywhere?

**Comment by nyteshade** [comment]
This did present an issue once. Seems like we should be able to fix that by making sure file names are quoted. Closing for now.

**Comment by BartmanAbyss** [comment]
Unfortunately `gnumake` doesn't cope with spaces in filenames at all. nothing to fix, I'm afraid.
