### ISSUE TITLE
endcli CloseWorkBench pair doesn't free up any memory

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#48]
I thought I would try endcli/CloseWorkBench to free up some chipmem on the A500 config.

However, it didn't seem to improve how much memory I can allocated with AllocMem(... , MEMF_CHIP). The largest size I can allocate is 427k in both cases.

Am I doing something wrong or is that to be expected?

I vaguely remember that kick1.3 might not close the workbench all the way.

Is there any other way to improve the chipmem I can allocate?

**Comment by BartmanAbyss** [comment]
I never tried myself. Did you compare the numbers `AvailMem(MEMF_CHIP|MEMF_TOTAL)` returns (instead of `MEMF_LARGEST`? Maybe the additional memory is just not continuous? See [here](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node0337.html)

**Comment by rjobling** [comment]
That should have occurred to me!

So, it does work, it's just slightly annoying!

Before
Chip Avail: 438184 (438184 largest)
Fast Avail: 452264 (443304 largest)

After
Chip Avail: 479272 (438184 largest)
Fast Avail: 453496 (443304 largest)
