### ISSUE TITLE
Steps for building the vsix file?

### ISSUE THREAD

**Issue by nyteshade** [BartmanAbyss/vscode-amiga-debug#49]
In order to contribute to the project, it would be nice to know how to set up a dev environment so we can best provide you with PRs that you'll likely approve and merge. 

I presume it starts with 

1. Make sure you have Ubuntu WSL installed
2. Install NVM and latest NodeJS version (14?) 
3. Clone the repo and cd into it
4. npm install
5. ??

I saw some steps on requirements on the README.md for porting, but this is different. What do we have to have present in order to contribute. Help me and I'll add a wiki page to the repo for others to follow.

The supplied scripts in the package.json file are as follows:

```json
{
	"scripts": {
		"vscode:prepublish": "concurrently -r \"npm:compile:ext\" \"webpack --mode=production\"",
		"compile": "concurrently -r \"npm:compile:*\"",
		"compile:ext": "tsc -p ./",
		"compile:client": "webpack --mode=development",
		"watch": "concurrently -r \"npm:watch:*\"",
		"watch:ext": "tsc -watch -p ./",
		"watch:client": "webpack --watch --mode=development --info-verbosity verbose",
		"serve": "webpack-dev-server --mode=development",
		"pretest": "npm run compile:ext",
		"test": "node ./out/test/runTest.js"
	}
}
```

None of these create a vsix file for testing.

**Comment by BartmanAbyss** [comment]
Hi,
you don't need to use WSL if you just want to compile the extension.
Just install the latest node.js, clone the repo and `npm install`.
Then open the directory in VS Code and hit `F5`. You can then test the extension without building a `.vsix`.
To build a `.vsix`, `npm install -g vsce` (once), `vsce package`.

**Comment by BartmanAbyss** [comment]
I'll put it into the README.

**Comment by BartmanAbyss** [comment]
fixed in https://github.com/BartmanAbyss/vscode-amiga-debug/commit/f490e6928d9f8d0fdc82a141ac10f830ed5b0138
