### ISSUE TITLE
Ability to have the extension create directories and place assets

### ISSUE THREAD

**Issue by sacredbanana** [BartmanAbyss/vscode-amiga-debug#50]
Hi

I was wondering if it would be possible to add a feature where every directory and file inside a special folder in the project automatically gets deployed onto the virtual amiga hard disk rather than having to manually put them in there yourself.

This would make life so much easier! Thanks!

**Comment by nyteshade** [comment]
Agreed. I was going to suggest we have one DH0 folder for each Kickstart. Thus would make 1.3/3.x changes easier.

**Comment by nyteshade** [comment]
You can put files into the DH0 directory in the vscode extensions folder.

**Comment by sacredbanana** [comment]
I already knew that we could put files in the extension's DH0 directory but that's a hassle to maintain, also I'm guessing every time the extension gets updated, everything in the DH0 folder will be wiped

**Comment by BartmanAbyss** [comment]
The directory containing your EXE file is automatically mounted as DH1, which is set as the current directory when your EXE is launched.
