### ISSUE TITLE
ADF creation

### ISSUE THREAD

**Issue by sacredbanana** [BartmanAbyss/vscode-amiga-debug#51]
Would it be possible to add the ability to create a bootable ADF containing the compiled app along with its required assets as long as it fits onto a floppy?

**Comment by BartmanAbyss** [comment]
Do you have a requirement for a non-DOS/trackloader? If not, why don't you just use a command-line tool or a Total Commander plugin to get your files in an ADF file? I'm not sure how the extension could be of use here.

**Comment by petmac** [comment]
You can use a tool like `adftool` for this:

https://amitools.readthedocs.io/en/latest/tools/xdftool.html

Untested but try something like:
```
xdftool mygame.adf format MyGame ffs + boot install + write a.mingw.exe mygame + makedir S + write startup-sequence S/startup-sequence
```

startup-sequence:
```
mygame
```

**Comment by BartmanAbyss** [comment]
see #122
