### ISSUE TITLE
The Player binary file

### ISSUE THREAD

**Issue by blitmaps** [BartmanAbyss/vscode-amiga-debug#57]
Hi There!

Would anyone happen to have the build steps to assemble "player610.6.no_cia.bin" (used in the example main.c).  I can load the bin that ships with The Player 6.1A, but cannot seem to create a viable binary without CIA.

Any help would be appreciated

**Comment by BartmanAbyss** [comment]
Hey,
I just downloaded the source (see README.md), and changed the following settings at the start of `610.6.asm`:
```
example = 0	;0 = assemble the pure replay
asmone = 1	;0 = Devpac, PhxAss and the like
system = 0	;0 = killer
CIA = 0		;0 = CIA disabled - Tempo commands are skipped !!
```
and built it with ASM-One v1.48

**Comment by blitmaps** [comment]
Cheers!

I will hit this up now, I was using the 1.49 and I got issues.

**Comment by blitmaps** [comment]
For the sake of completeness, this worked great - I have shouted out Abyss in my game trailer.
