### ISSUE TITLE
Workbench > app

### ISSUE THREAD

**Issue by bpoynton** [BartmanAbyss/vscode-amiga-debug#59]
Is it possible to load Workbench and then run/debug the app? Reason I ask is I want to test an app in a full Workbench environment to assess multitasking, available memory etc.

I have copied a previously fresh install into the dh0 folder and adjusted the startup-sequence, but the startup-sequence gets overwritten on run from VSCode every time with just the 'cd dh1: :a.mingw.exe' commands.

Any help appreciated!

**Comment by BartmanAbyss** [comment]
Hi, this is not supported. As you already have found out, a new startup-sequence is generated every time to directly execute your app. You can modify the extension source code to generate a different startup-sequence. Is this something that can help you?

**Comment by bpoynton** [comment]
I commented out the lines in amigaDebug.ts that generate startup-sequence (this will break if 'debugging_trigger' ever changes - but I'll worry about that later), copied a WB install to DH0, updated the startup-sequence to run 'cd dh1: :a.mingw.exe', rebuilt and re-installed the .vsix (struggled to run & debug the extension as when hitting F5 as described in the README VSCode just hangs in 'building' state for a loooong time).

It runs and the debugger connects, resolves breakpoints etc. as expected but the Profiler reports only DMA and fails multi-frame grabs. I don't have the knowledge to go any further so will leave it here, if you think it might be an obvious fix then please let me know, otherwise this issue can be closed as I have basically achieved what I need.

Thank you!

**Comment by bpoynton** [comment]
Scratch that! I have no idea how but was working from commit 8903e15, after fetching latest (ae5ba2c) the Profiler is working as expected.

Closing
