### ISSUE TITLE
gnumake clean error

### ISSUE THREAD

**Issue by hsarret** [BartmanAbyss/vscode-amiga-debug#6]
Hi Bartman,
First thing first, **nice job** on this Amiga tool :)
I started using it lately and noticed an error while trying to use command **gnumake clean**
![image](https://user-images.githubusercontent.com/2386622/83653684-5c591c80-a5bc-11ea-85c3-6dec0a94d623.png)
Using plugin **1.0.0** with VSCode **1.45.1** on a Windows 10 64 bits machine
Let me know if you need more informations or help
Cheers
Kyle/MenTaSm

**Comment by BartmanAbyss** [comment]
Hi,
gnumake doesn't like spaces in directories. maybe it also has problems with the "dash" in your directory name. Also, I'm not sure why there is a mention of /usr/bin/bash in your output. maybe there is some CygWin or WSL in your PATH?

**Comment by hsarret** [comment]
Tried with a new project in **c:\test** and had same issue
I do have WSL but not cygwin
Following is what I get when I issue a **where** command for **bash**
_λ where bash
C:\Windows\System32\bash.exe
C:\Users\hsarret\cmder\vendor\git-for-windows\bin\bash.exe
C:\Program Files\Git\usr\bin\bash.exe
C:\Users\hsarret\cmder\vendor\git-for-windows\usr\bin\bash.exe_

**Comment by hsarret** [comment]
Looks like somehow it runs clean command in bash and ver command is not available there

**Comment by hsarret** [comment]
Adding following line at top of Makefile fix issue
_**SHELL = cmd.exe**_

**Comment by hsarret** [comment]
Reading https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html
If I understood correctly it should use my comspec environment variable and use cmd.exe
**_ComSpec=C:\WINDOWS\system32\cmd.exe_**

**Comment by BartmanAbyss** [comment]
Yeah, that's strange, but glad this fixes it for you
