### ISSUE TITLE
Setting up The Player at link time

### ISSUE THREAD

**Issue by blitmaps** [BartmanAbyss/vscode-amiga-debug#62]
Hey, I haven't issued a PR as I don't know if you're interested / didn't want to mess with the generic template; however I have done some work making The Player work better in the toolchain.

1. I am using the new(ish) version by Photon - p6112
2. I am wrtiting the xdef in assembler before assembling like this:
```
	xdef PlayRun
PlayRun:
	movem.l d0-a6,-(sp)
	lea incbin_mymod_start,a0
	jsr ThePlayerStart
	movem.l (sp)+,d0-a6
	rts

ThePlayerStart:
	sub.l a1,a1
	sub.l a2,a2
	moveq #0,d0
	lea p61coppoke+3,a4		;only used in P61mode >=3
	jsr P61_Init
	rts
	xref incbin_mymod_start
```

3. I then use vasm to make a binary:
`vasm -Felf my_player.asm`

4. Then, the xref reference can be defined, and the xdef called in the C++:

```
// This gets exported as the symbol incbin_mymod_start, so our assembly will see it.
INC_BIN(mymod, "P61.mymod")

// This will allow us to call our assembly
extern "C" void PlayRun();
```

5.  Then we can just add the player elf to the make command before it gets hunked, and we are golden.

`@$(CC) $(CCFLAGS) $(LDFLAGS) $(objects) player610.o obj/gcc8_a_support.o -o $@
`

**Comment by BartmanAbyss** [comment]
Hi, this is certainly an interesting alternative. I included ThePlayer in the sample project just to illustrate how you can use a binary player without recompilation. I think that's easier for most people.

**Comment by blitmaps** [comment]
For sure, I've had a right headache getting it working right.  I still haven't got vasm in the toolchain, I just built it externally.  btw, thanks for the toolchain, my game would not have been possible without it!

**Comment by resom-d** [comment]
Hi guys,
I'm trying to use the player coming with the vscode extension. But my converted tracks play much too slow if I set the tempo of the song via a tracker command - even the 'newDitty' mod by photon does the same thing. I use PT315 and have also tried PT361 - but the result is the same. If tempo is not changed all seems good. Any hints what I might do wrong?
Regards
Hank
