### ISSUE TITLE
Minimal project in repo keeps on 'Building'

### ISSUE THREAD

**Issue by MiguelAtTweddle** [BartmanAbyss/vscode-amiga-debug#64]
When following the steps of the README.md and setting the rom path in the launch.json the minimal project setup in this repo keeps in 'Building' status and never gets executed.
Also the Command Palette doesn't show options like: Amiga: View Memory, Amiga: Set Force Disassembly, Amiga: View Disassembly (Function)

**Comment by BartmanAbyss** [comment]
Have you checked the Terminal window "Task - compile"? The debugging commands only show up during debugging.
