### ISSUE TITLE
getSymbols hangs

### ISSUE THREAD

**Issue by Muzza** [BartmanAbyss/vscode-amiga-debug#67]
Hi,
Whilst experimenting with this extension my program failed to launch with no error message. Debugging the extension found that it was getting stuck in getSymbols. It seems my program was producing a lot of symbol output and the call to childProcess.spawnSync has a limit of how much it will read before just killing the process.
Adding a 'maxBuffer' parameter fixed it:
`const objdump = childProcess.spawnSync(this.objdumpPath, ['--syms', '--demangle', this.executable],{maxBuffer: 1024 * 1024 * 128});`

**Comment by BartmanAbyss** [comment]
Thanks for the fix. This was the only place that was missing the `maxBuffer` option ;)
