### ISSUE TITLE
Resource view bitmap modes?

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#72]
I love the resource view and being able to see the blits as they happen.

I'd love it even more if I could specify the screen mode.

Being able to see the resource in HAM5/6 or Dual-playfield or Half-bright would be very helpful!

**Comment by BartmanAbyss** [comment]
sure. if you can send me a sample project I can build an run in the profiler with the new screen modes, I will take a look at adding them.

**Comment by rjobling** [comment]
I made a test project for HAM5/6 and EHB and sent you an invite.

At the top of ham.cpp there are defines you can use to toggle the mode it compiles for.

I didn't add dual-playfield because I don't think I'll need that, I would just register two separate bitmaps.

**Comment by BartmanAbyss** [comment]
fixed in https://github.com/BartmanAbyss/vscode-amiga-debug/commit/870c12ea2710178919fd6d9dd6c72b5f0aaff64d https://github.com/BartmanAbyss/vscode-amiga-debug/releases/tag/1.1.0-preview42

**Comment by rjobling** [comment]
Thanks for this update!! I grabbed the new installed and it's working great. One minor issue is that it uses black for the initial color. I suspect my test project had a black background color. However my current project does not, and so it's not showing up 100% correctly. Hopefully that's an easy fix and just need to initial prev color set to the same are palette entry color[0].

**Comment by BartmanAbyss** [comment]
Yes, you‘re right. Will fix tomorrow.

**Comment by BartmanAbyss** [comment]
Fixed in https://github.com/BartmanAbyss/vscode-amiga-debug/commit/0590b2e9d6f9ad3bd7561f7b963f4a3c0d6d41d4 (1.1.0-preview43)
