### ISSUE TITLE
Foreign characters support in path

### ISSUE THREAD

**Issue by rchyla** [BartmanAbyss/vscode-amiga-debug#74]
Hi.

It took few days to investigate this, i am amateur. I coudn't make run the example code as WinUAE was giving me constantly error of not finding the disk in drive DH0.

As it turned out, my windows profile contains one polish letter "ł", but the extension is transforming it to "Ĺ‚" when DH0 path for  WinUAE is generated.

It is:
`c:\Users\RafaĹ‚\.vscode\...`

should be
` c:\Users\Rafał\.vscode\...`

Temporal solution, copy this extension folder somwhere where path doesn't contain language related characters, edit amigaDebug.ts, find the following line 
`
const dh0Path = path.join(binPath, "dh0");`

replace `binPath` with the path to `bin` folder inside copied extension folder, compile and install from vsix, the path is hardcoded now into the extension.

**Comment by BartmanAbyss** [comment]
You got the sample project to compile? I renamed my `amiga-debug` directory to `amiga-debugł` and couldn't even compile the project. I think those unix tools (gnumake, gcc, etc.) don't really support unicode pathes on windows (see https://stackoverflow.com/questions/24136767/makefile-gcc-struggles-with-special-characters-in-path-using-windows).
So, sorry about that.

**Comment by rchyla** [comment]
I did compile it, but i used custom path for dh0Path as something constantly is misinterpreting that unicode character, this line looks like this:

const dh0Path = path.join("E:/projects/amiga_programy/VScode/extensions/bartmanabyss.amiga-debug-1.1.0-preview42/bin", "dh0");

To reproduce this problem, you have to create an account in Windows with unicode letter and install your extension on this profile. You can't change (easily) user path in Windows after account is created, that is why i had to copy extension to different drive and hardcode the path to dh0.

**Comment by BartmanAbyss** [comment]
Yeah, sorry. I tried again. However there are just so many problems with the GNU tools. Even if I use a prebuilt exe in a unicode-path, `objdump` fails before WinUAE even starts...

**Comment by rchyla** [comment]
No problem, just a warning on main page about unicode paths may save
someones life :)

**Comment by BartmanAbyss** [comment]
Fair enough. I‘ll add a check
