### ISSUE TITLE
Profiling cpu and hardware registers.

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#78]
Would it be possible to add the cpu registers to the profiler view so you can watch them change as the code in the assembly window changes?

Would it be possible to include changes to readable hardware registers, things like vposr/intenar/intreqr/dmaconr? Currently I only see vposw/intena/intreq/dmacon and they only update when written to (unsurprisingly). This would help debugging since you'd be able to see them change as you scrub the profile slider.

On a similar note is it possible to show the hardware registers inside the gdb debugger along with the existing cpu registers?

**Comment by BartmanAbyss** [comment]
> Would it be possible to add the cpu registers to the profiler view so you can watch them change as the code in the assembly window changes?

I'm currently not capturing the registers for each cycle, probably quite a bit of data. But I'll see what I can do.

> Would it be possible to include changes to readable hardware registers, things like vposr/intenar/intreqr/dmaconr? Currently I only see vposw/intena/intreq/dmacon and they only update when written to (unsurprisingly). This would help debugging since you'd be able to see them change as you scrub the profile slider.

I'm not actually storing the custom registers in the capture, but recreate them based on the DMA writes.. Have to think about this some more.

> On a similar note is it possible to show the hardware registers inside the gdb debugger along with the existing cpu registers?

I guess that's possible.

I'm currently quite busy preparing [the next vscode-amiga-debug seminar](https://deadline.untergrund.net/2021/events/#amiga_seminar), so I can have a look at these improvements in November at the earliest.

**Comment by rjobling** [comment]
Understood!

Maybe there is a subset of readable hardware registers worth recording without inflating the capture too much.

Hopefully that seminar will be broadcast or release shortly after! I've really loved using this system and the improvements!

**Comment by BartmanAbyss** [comment]
Yes, as far as I understand it the seminar will be streamed.
