### ISSUE TITLE
Profiler colors

### ISSUE THREAD

**Issue by T0lk13n** [BartmanAbyss/vscode-amiga-debug#81]
![BartMan vscode](https://user-images.githubusercontent.com/14197827/135745820-b9ef352e-ed1b-425c-a5e6-2b8aae3b523b.png)

Dont know why in the profiler I can get colors and is all black. I have changed vscode theme but without result.

PD. Note a few compilerpath errors

**Comment by BartmanAbyss** [comment]
Hmm.. no idea. If you hit `Ctrl+Shift+I` do you see any relevant errors in the console?

**Comment by T0lk13n** [comment]
Sorry for late response.
The only error I get is this when I switch to profiler: 
negative nr_color_changes: -2. FIXME!
