### ISSUE TITLE
KPrintF vs. fmt

### ISSUE THREAD

**Issue by apannwitz** [BartmanAbyss/vscode-amiga-debug#82]
Is it possible to print out an unsigned integer for debugging? The following does not work:

	unsigned int x=10;
	KPrintF("x=%u", x);

Did I miss something?

**Comment by BartmanAbyss** [comment]
yes, a bit unintuitively, the format specifiers are amiga-specific. See [here](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node036C.html). So in you're case you should use %ld (int = "l", decimal = "d"). %lu has been added with Kickstart 2.0, so it won't work with Kickstart 1.3
