### ISSUE TITLE
"endcli" only works 10% of the time?

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#86]
For reasons I don't understand using "endcli" set to "true" in the launch options means that my exe fails to launch inside WinUAE most of the time.

It'll get to the 1.3 cli window, which will close as expected but then the screen will just flash quickly before coming right back to the now empty workbench screen.

Seems I also need to have "uaelog" set to "false".

Any ideas?

**Comment by BartmanAbyss** [comment]
Nopes, sorry. Never really been using that feature.
