### ISSUE TITLE
ProTracker integration in the example code?

### ISSUE THREAD

**Issue by DrNoIDSwe** [BartmanAbyss/vscode-amiga-debug#9]
This was super easy to set up but it would be good to have integration with ThePlayer or another ProTracker replay routine in the example project as it is rather hard to get that one working with C (at least for me).

**Comment by BartmanAbyss** [comment]
Sure, good idea.I’ll whip something up.

**Comment by BartmanAbyss** [comment]
added ThePlayer61 example in 5c0dd7544899b69e04b88789229d773fed9e8038.
Just grab the new template project https://github.com/BartmanAbyss/vscode-amiga-debug/tree/master/template
