### ISSUE TITLE
AmigaOS 3.2 NDK instead of AmigaOS 3.9

### ISSUE THREAD

**Issue by RMonaghan-Illuscio** [BartmanAbyss/vscode-amiga-debug#93]
Hello,
Can someone suggest a way to use AmigaOS 3.2.x headers, rather than the older 3.9 headers?

thanks!

**Comment by BartmanAbyss** [comment]
As I wrote in the [README](https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/README.md) file, I just grabbed the headers out of an installation of bebbo's gcc toolchain and modified `amiga-debug\bin\opt\m68k-amiga-elf\sys-include\inline\macros.h` to work with a newer GCC. I currently do not have any plans on supporting 3.2 headers, but if you'd like, I would recommend the following workflow:
grab bebbo's toolchain with NDK 3.9, and check the differences between its include folder and mine. Then configure bebbo's toolchain with NDK 3.2 and check if you can merge them somehow.
