### ISSUE TITLE
Incorrect cycle times?

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#96]
Love the new additions but some of the cycle counts seem wrong.

This should be 8 cycles not 18, I think:
![image](https://user-images.githubusercontent.com/5326134/167733224-a12de879-4182-4690-9216-5c93f1fe3631.png)

This also seems wrong, EASy68k reports 22cycles:
![image](https://user-images.githubusercontent.com/5326134/167734973-0205389b-b12e-4c00-85d8-b6f4c00382f3.png)

I don't know these numbers well, so I'm going off what EASy68k tells me. I suppose it could be wrong in the second case.

**Comment by BartmanAbyss** [comment]
Haha, nice find. Seems the `lea` opcode only has problems with `a5` as source register ;)

**Comment by BartmanAbyss** [comment]
For `bchg`, [68000 user's manual](https://www.nxp.com/docs/en/reference-manual/MC68000UM.pdf) pg. 136 says for _dynamic, memory_ 8 + EA (=10). So I would say, EASy68k is wrong, it seems to take from the column _static, memory_ but that refers to something like `bchg #3,(a4,d3.w)`.

**Comment by rjobling** [comment]
> For `bchg`, [68000 user's manual](https://www.nxp.com/docs/en/reference-manual/MC68000UM.pdf) pg. 136 says for _dynamic, memory_ 8 + EA (=10). So I would say, EASy68k is wrong, it seems to take from the column _static, memory_ but that refers to something like `bchg #3,(a4,d3.w)`.

My code just got faster :)
