### ISSUE TITLE
Profiler seems to crash when looking at assembly and scrubbing through the time line.

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#97]
I don't know if this is unique to my project but if I try to watch the assembly tab and scrub the time from left to right then it freezes and never recovers.

**Comment by BartmanAbyss** [comment]
Can you upload the .amigaprofile file? I‘ll have a look.

**Comment by rjobling** [comment]
This one consistently gives me trouble:

[assembly_scrub_crash.zip](https://github.com/BartmanAbyss/vscode-amiga-debug/files/8800578/assembly_scrub_crash.zip)
